services:
  postgres:
    image: postgres:18.4-alpine3.23
    container_name: restock-db
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_DEV}
    ports:
      - "5432:5432"
    volumes:
      - restock_db:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - restock_network

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: restock-backend
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER_DEV}:${DATABASE_PASSWORD_DEV}@${DATABASE_HOST_DEV}:${DATABASE_PORT_DEV}/postgres"
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "3010:3010"
    volumes:
      - restock_backend:/app
      - ./apps/api/src:/app/apps/api/src
    restart: always
    networks:
      - restock_network
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    container_name: restock-frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - restock_frontend:/app
      - ./apps/web/app:/app/apps/web/app
      - ./apps/web/public:/app/apps/web/public
    restart: always
    networks:
      - restock_network

networks:
  restock_network:
    driver: bridge

volumes:
  restock_db:
  restock_backend:
  restock_frontend:
